---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ab-deployment-a
  labels:
    deployment: abdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: abdeploy
  template:
    metadata:
      labels:
        deployment: abdeploy
    spec:
      containers:
        - name: abdeploy
          image: color:0.0.1
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: COLOR
              value: red

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ab-deployment-b
  labels:
    deployment: abdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: abdeploy
  template:
    metadata:
      labels:
        deployment: abdeploy
    spec:
      containers:
        - name: abdeploy
          image: color:0.0.1
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: COLOR
              value: green

---
apiVersion: v1
kind: Service
metadata:
  name: scale-test-lb
spec:
  selector:
    deployment: abdeploy
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
  type: LoadBalancer