---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-test
  labels:
    deployment: nginx-hello
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: nginx-hello
  template:
    metadata:
      labels:
        deployment: nginx-hello
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello
        # image: nginx:1.14.2
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: scale-test-lb
spec:
  selector:
    deployment: nginx-hello
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  type: LoadBalancer